### ISSUE TITLE
Launch stack uses an outdated .yml file

### ISSUE THREAD

**Issue by jcgohr** [m-chandler/factorio-spot-pricing#47]
After #41, you should be able to disable the space age dlc when deploying the CloudFormation.

However the launch stack button in the `README.md` uses an outdated version of the file without the space age parameter.
[![Launch Stack](https://s3.amazonaws.com/cloudformation-examples/cloudformation-launch-stack.png)](https://console.aws.amazon.com/cloudformation/home#/stacks/new?stackName=factorio&templateURL=https://s3.amazonaws.com/factorio-spot-pricing/cf.yml)

The current version of the file: [https://github.com/m-chandler/factorio-spot-pricing/blob/master/cf.yml](https://github.com/m-chandler/factorio-spot-pricing/blob/master/cf.yml) has this block which allows the user to enable/disable the space age dlc.
```yml
  DlcSpaceAge:
    Type: String
    Description: Refer to https://hub.docker.com/r/factoriotools/factorio/ for further information about Space Age. Enables or disable Space Age mods. Everybody that wants to use these servers will have to have mods enabled or disabled respectively for the Space Age expansion pack. Irrelevant if docker image for factorio is set to be prior to v2.
    Default: false
    AllowedValues:
    - true
    - false
```

The AWS version (located at [https://s3.amazonaws.com/factorio-spot-pricing/cf.yml](https://s3.amazonaws.com/factorio-spot-pricing/cf.yml) or [https://factorio-spot-pricing.s3.amazonaws.com/cf.yml](https://factorio-spot-pricing.s3.amazonaws.com/cf.yml)) is **outdated** and does not provide the option to disable the space age dlc.

I suppose this could be circumvented by uploading the template or syncing with git but I believe it would prevent some headache for those users without the space age dlc.
